### ISSUE TITLE
Transport vs Endpoint

### ISSUE THREAD

**Issue by RandyGaul** [networkprotocol/reliable.io#1]
Hi Glenn,

Quick question. Could you explain the conceptual difference between the terms [endpoint](https://github.com/networkprotocol/reliable.io/blob/master/reliable.c#L407) and [transport](https://github.com/networkprotocol/yojimbo/blob/aff630801c6124043fc84cd342ecfadccb3cee4a/yojimbo_transport.h#L211) in the context of yojimbo/reliable.io?

Thanks!

**Comment by gafferongames** [comment]
Well an endpoint is simply one side of a connection wrt. to the reliability system, for example, check out the new yojimbo experimental branch to see an example of usage. Transport is the actual sending and receiving of packets, and is actually going away in new yojimbo design, as that is now handled exclusively by netcode.io
