### ISSUE TITLE
Pure rust port

### ISSUE THREAD

**Issue by jaynus** [networkprotocol/reliable.io#12]
In line with my other issue posted to netcode.io, I have implemented a functionally complete pure rust implementation of reliable.io @ https://github.com/jaynus/reliable.io

The code is still a bit immature and undocumented and a crate isn't mature to push yet; but it is complete and working and worth noting, if you'd like to. I will be pushing it to crates once it is further tested in an actual implementation.

**Comment by gafferongames** [comment]
This is awesome! Thanks! Please create a pull request for the README.md for this project linking to yours. Thanks again!
