### ISSUE TITLE
Need hints on how to handle packet re-transmission.

### ISSUE THREAD

**Issue by aghiles** [networkprotocol/reliable.io#14]
Reading the docs and the code (no comments!), I am not sure how to proceed. So I am sending a packet over UDP using a reliable "endpoint". Does reliable.io handles re-transmission, I see that reliable_endpoint_receive_packet does some ACK computations but never writes back to sending endpoint.   I think a step-by-step explanation would do wonder for this little library.

**Comment by gafferongames** [comment]
reliable.io just tells you which packets were received. You can build reliability on top of that. See yojimbo for an example. https://github.com/networkprotocol/yojimbo

**Comment by aghiles** [comment]
Thank you for your reply. 

Can you just let me have more questions here before closing the issue ? I think it would be very useful for future users. I want to use reliable.io but having a look at Yojimbo, a much larger project which is much  harder to understand, discourages me for going ahead. I think reliable.io should be self-contained API/Documentation wise. I can help with that if I just manage to understand some very basics.

My usage case is packets smaller than MCU ( "packet_bytes <= endpoint->config.fragment_above" ), and my question are all about ACK. For example:

1- When using reliable_endpoint_tranfer_packet(), how do I know that the packet got through?  I see the "transmit" function is called but there is nothing to signal that anything was transmitted. Which leads to :
2- Should I rely on the other endpoint replying some information  and should I do that myself ? Which leads to:
3- This probably means that I need to maintain some form of buffers/timers/queues to re-transmit the packets?

Thank you for your patience.

**Comment by gafferongames** [comment]
There is no concept of packet retransmission. Each packet you send has a sequence number. Reliable.io tells you which packets were received by the other side. If you want a packet to get through reliabliy, all you need to do is keep resending its data in new packets (reliable.io never "resends" a packet), until you get an ack that that packet has been received.

cheers

**Comment by aghiles** [comment]
I understand better now !

Last question: by which mechanism "reliable.io tells you which packets were received by the other side". That's the part that I am missing. 

Is it somehow by calling "reliable_endpoint_clear_acks" ? 

I think with this information I could proceed. I will write up something that could maybe be added to the README.

**Comment by gafferongames** [comment]
reliable_endpoint_get_acks

after you get the array of acks (list of 16bit sequence #s that have been received by the other side), you call:

reliable_endpoint_clear_acks

**Comment by aghiles** [comment]
Understood!  

I am trying to find the mechanism that sends back ACK signals to the the other endpoint. I can't find it. It must use the "transfer" config method I guess? 
Thanks for your help.
