### ISSUE TITLE
Shouldn't this be "context.receiver" ?

### ISSUE THREAD

**Issue by aghiles** [networkprotocol/reliable.io#15]
https://github.com/networkprotocol/reliable.io/blob/c22dbd8f1161d3ca74529aa1f564e19e3735bb10/reliable.c#L1818

**Comment by gafferongames** [comment]
Nice find. Yes, it's a cut & paste bug. Please submit a pull request w. fix!

**Comment by aghiles** [comment]
OK. Tomorrow should be good.

**Comment by gafferongames** [comment]
ETA?

**Comment by aghiles** [comment]
Sorry about being late with this. Give I will do this today.
