### ISSUE TITLE
How does reliable deals with duplicates ?

### ISSUE THREAD

**Issue by aghiles** [networkprotocol/reliable.io#19]
I am no sure duplicates are dealt with internally. For example, re-=sending the same packet twice (because ACKs did not arrive) could lead to receive packet duplications. If possible, could someone shed some light on this ?

**Comment by gafferongames** [comment]
reliable.io does not resend dropped packets, it simply tells you which packets were received by the other side.

**Comment by gafferongames** [comment]
(So yes, all handling of resending dropped packets, and handling duplication is up to you!)
