### ISSUE TITLE
Should a packet re-transmission be sent as a new packet?

### ISSUE THREAD

**Issue by sro5h** [networkprotocol/reliable.io#20]
I am currently playing around with this library and trying to understand how to handle packet retransmission.

Let's suppose i send a packet with sequence X, i don't get an ack in for some time and decide to resend it. After reading issue #14 i think i should send a new packet with sequence number Y and it is my responsibility to remember that packets with sequence numbers X and Y are actually the same. 

This seems rather inconvenient, increasingly so with multiple re-transmissions of the same packet.
Is this how this library is supposed to be used?

**Comment by gafferongames** [comment]
Yes, this library tells you what packets were received. It's up to you to implement your own reliability using that knowledge. It's a low-level library, meant to be used as the foundation of other libraries. It's not meant to be convenient for you. :)

**Comment by sro5h** [comment]
Ok fair enough, it is to be expected from a low level library :) thanks for the clarification.
I'll try to figure out how yojimbo handles re-transmits. As far as I understand the correct place to look at would be `ReliableOrderedChannel`?

**Comment by gafferongames** [comment]
You won't find what you are looking for in yojimbo. Yojimbo doesn't retransmit dropped packets. Instead, it sends packets x times per-second, and includes unpacked *messages* in outgoing packets. It's more efficient than a traditional resend un-acked packet approach, when the majority of your packets are unordered, unreliable data. -- cheers
