### ISSUE TITLE
open to a javascript port?

### ISSUE THREAD

**Issue by mreinstein** [networkprotocol/reliable.io#6]
I've got a port nearly finished, including all of your unit/soak/fuzz tests (which pass!) The only thing remaining is to put in packet fragmentation/re-assembly.  Would you be willing to link to it in this project's README?

I intend to keep it a faithful port in terms of structure and naming.

Totally happy to add you (and/or anyone you designate as qualified) as a maintainer.

I'd also like to publish this to npm

**Comment by mreinstein** [comment]
what I have so far:  https://github.com/mreinstein/reliable.io.js

**Comment by gafferongames** [comment]
Wow! Sounds great!

**Comment by gafferongames** [comment]
I'll add a link to your port from the main page. Thanks!
