### ISSUE TITLE
why isn't there an acked_packet_function callback?

### ISSUE THREAD

**Issue by mreinstein** [networkprotocol/reliable.io#8]
I see 2 callback functions defined:

`void (*transmit_packet_function)(void*,int,uint16_t,uint8_t*,int);` is fired whenever a packet is ready to be sent. it's implementation should handle actually sending data over the socket.

`int (*process_packet_function)(void*,int,uint16_t,uint8_t*,int);` is fired whenever a packet is received (either a regular packet or a fragmented packet that's been fully re-assembled)

I'm surprised that there is no callback function that is invoked whenever a packet goes from non-acked -> acked. Isn't this the kind of callback one would need to build a reliable message system on top of reliable.io ?  Otherwise you'd have to duplicate all of https://github.com/networkprotocol/reliable.io/blob/master/reliable.c#L1090-L1120 logic inside your `process_packet_function`. Or is there a better way to handle this?

**Comment by gafferongames** [comment]
The idea is that once per-frame you are able to query the set of acks from reliable.io, it gives you a list of all sequence numbers that were acked. Does this help?

**Comment by gafferongames** [comment]
For example, look at:

uint16_t * reliable_endpoint_get_acks( struct reliable_endpoint_t * endpoint, int * num_acks );

void reliable_endpoint_clear_acks( struct reliable_endpoint_t * endpoint );

The idea is that once per-frame, you call reliable_endpoint_get_acks, then when you are done with this, you call reliable_endpoint_clear_acks.

cheers

**Comment by mreinstein** [comment]
> The idea is that once per-frame you are able to query the set of acks from reliable.io, 
> it gives you a list of all sequence numbers that were acked

So basically per frame:
1  call `reliable_endpoint_get_acks()` to get the currently acked sequence numbers
2 compare `last_acked` to the current acks, and for any sequence numbers that are now acked, handle them
3 set `last_acked` to the current acks
4 go to 1

?

**Comment by mreinstein** [comment]
ah, nevermind I get it now. So basically in each endpoint there is `num_acks` and `acks[]`, so these get buffered internally. It's the responsibility of the caller to read these out and reset the acks. If this buffer fills up completely, it will start dropping acks.

**Comment by mreinstein** [comment]
one thing that strikes me as odd: `transmit_packet_function` and `process_packet_function` are callbacks, but the ack getting/clearing is essentially poll based. Is this an inconsistency in the API or an intentional design decision?

**Comment by jakecoffman** [comment]
@mreinstein those aren't asynchronous callbacks, they will be called immediately when send/receive_packet are called. In the case of `transmit_packet_function`, it is called once for each fragment. They are just for providing your own implementation of sending/receiving packets.
